### ISSUE TITLE
Signals.sh creates empty fripm result file and doesn't create visualisations

### ISSUE THREAD

**Issue by PetrTsurinov** [JetBrains-Research/washu#57]
Some problems appeared during execution signals.sh for input files 
`bash /mnt/stripe/washu/downstream/signals/signals.sh /mnt/stripe/bio/raw-data/aging/input/ 150 /mnt/stripe/bio/raw-data/aging/loci_of_interest/hg19_1000.bed /mnt/stripe/bio/genomes/hg19/hg19.chrom.sizes /mnt/stripe/bio/raw-data/aging/input/zinbra/input_zinbra_median_consensus.bed`
1) Fripm and manorm results files are empty
2) Script failed to created visualisations: "Failed to visualize /mnt/stripe/bio/raw-data/aging/input/150//hg19_1000/hg19_1000_raw.tsv"

Results can be found at `/mnt/stripe/bio/raw-data/aging/input/signals/hg19_1000`

**Comment by olegs** [comment]
Closing as won't fix, since signals functionality requires input.
