### ISSUE TITLE
rip.sh only supports BAMs

### ISSUE THREAD

**Issue by dievsky** [JetBrains-Research/washu#58]
`scripts/rip.sh` only accepts BAM files, but we sometimes have data in other formats, e.g. `.bed.gz`.

**Comment by olegs** [comment]
I think we should cleanup `.bed.gz` or remove this functionality at all.

**Comment by olegs** [comment]
Decompressed BED files are places in a dedicated subdirectory (like `./pileup` for BAMs) for easier cleanup. The same approach is implemented for BAM pileups.
