### ISSUE TITLE
Unable to pull biolabs/uli-pipeline docker image

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/washu#69]
```
unit-809:fastq oleg$ docker run -v ~/work/washu:/washu -v $(pwd):/data -e WASHU_ROOT=/washu -e LOCAL_USER_ID=`id -u $USER` -it biolabs/uli-pipeline /bin/bash -c "bash /washu/pipeline_chipseq.sh"
Unable to find image 'biolabs/uli-pipeline:latest' locally
docker: Error response from daemon: pull access denied for biolabs/uli-pipeline, repository does not exist or may require 'docker login'.
```

**Comment by olegs** [comment]
Yep, I haven't built it locally. Closing the issue. 
> Also, the data folder should be the parent folder of `fastq`, since the pipeline looks for FASTQ files in `/data/fastq`. - Original pipeline works differently I guess the reason of this is to make parent folder writable. Can you please explicitly mention this?

**Comment by dievsky** [comment]
Added a working directory hint to README.
