### ISSUE TITLE
ChipSeq pipeline: Zero GAP for SICER is used for H3K36me3 GSE112622

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/washu#72]
ChipSeq pipeline: Zero GAP for SICER is used: see chipseq pipeline sources + GSE112622 SICER peak calling results. Should be > 0 for long marks like H3K36me3, Galaxy suggests 600 bp as default.

![image](https://user-images.githubusercontent.com/72933/48484737-fcf3ba00-e827-11e8-9c58-cf1e6405629b.png)

![image](https://user-images.githubusercontent.com/72933/48484760-0bda6c80-e828-11e8-9b42-756349e45353.png)

**Comment by olegs** [comment]
Fixed as of 7934cc1185dec50f0774e77affe715688cd9fa40
