### ISSUE TITLE
ValueError: cannot resize this array: it does not own its data

### ISSUE THREAD

**Issue by hemantgujar** [JetBrains-Research/washu#78]
Hi 

I am still getting this error. According to one of the thread https://github.com/JetBrains-Research/washu/issues/14 in 2017 this can be ignored. is it still true or was this fixed ?

What is causing this problem and How do i fix this ?

Thank you 

$ `macs2 --version`
macs2 2.2.7.1

INFO  @ Wed, 18 Nov 2020 19:37:42: 
# Command line: callpeak -t /project/xx_71/xx/XX1/ccc/ccc_cancer/hhh/ChiP_LData/raw_data/bam_files/A1EVK4D0.clean_sorted.bam -c /project/xx_71/xx/XX1/ccc/ccc_cancer/hhh/ChiP_LData/raw_data/bam_files/F1EVD0IP.clean_sorted.bam -f BAM -g hs -n A1EVK4D0.F1EVD0IP -B -q 0.01
# ARGUMENTS LIST:
# name = A1EVK4D0.F1EVD0IP
# format = BAM
# ChIP-seq file = ['/project/xx_71/xx/XX1/ccc/ccc_cancer/hhh/ChiP_LData/raw_data/bam_files/A1EVK4D0.clean_sorted.bam']
# control file = ['/project/xx_71/xx/XX1/ccc/ccc_cancer/hhh/ChiP_LData/raw_data/bam_files/F1EVD0IP.clean_sorted.bam']
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 1.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 1000 bps and 10000 bps
# Broad region calling is off
# Paired-End mode is off
 
INFO  @ Wed, 18 Nov 2020 19:37:42: #1 read tag files... 
INFO  @ Wed, 18 Nov 2020 19:37:42: #1 read treatment tags... 
INFO  @ Wed, 18 Nov 2020 19:37:45:  1000000 
INFO  @ Wed, 18 Nov 2020 19:37:48:  2000000 
INFO  @ Wed, 18 Nov 2020 19:37:51:  3000000 
INFO  @ Wed, 18 Nov 2020 19:37:54:  4000000 
INFO  @ Wed, 18 Nov 2020 19:37:57:  5000000 
INFO  @ Wed, 18 Nov 2020 19:38:00:  6000000 
INFO  @ Wed, 18 Nov 2020 19:38:03:  7000000 
INFO  @ Wed, 18 Nov 2020 19:38:06:  8000000 
INFO  @ Wed, 18 Nov 2020 19:38:09:  9000000 
INFO  @ Wed, 18 Nov 2020 19:38:12:  10000000 
INFO  @ Wed, 18 Nov 2020 19:38:15:  11000000 
INFO  @ Wed, 18 Nov 2020 19:38:18:  12000000 
INFO  @ Wed, 18 Nov 2020 19:38:21:  13000000 
INFO  @ Wed, 18 Nov 2020 19:38:24:  14000000 
INFO  @ Wed, 18 Nov 2020 19:38:27:  15000000 
INFO  @ Wed, 18 Nov 2020 19:38:30:  16000000 
INFO  @ Wed, 18 Nov 2020 19:38:34:  17000000 
INFO  @ Wed, 18 Nov 2020 19:38:37:  18000000 
INFO  @ Wed, 18 Nov 2020 19:38:40:  19000000 
INFO  @ Wed, 18 Nov 2020 19:38:43:  20000000 
INFO  @ Wed, 18 Nov 2020 19:38:46:  21000000 
INFO  @ Wed, 18 Nov 2020 19:38:49:  22000000 
INFO  @ Wed, 18 Nov 2020 19:38:52:  23000000 
INFO  @ Wed, 18 Nov 2020 19:38:55:  24000000 
INFO  @ Wed, 18 Nov 2020 19:38:59:  25000000 
INFO  @ Wed, 18 Nov 2020 19:39:02:  26000000 
INFO  @ Wed, 18 Nov 2020 19:39:05:  27000000 
INFO  @ Wed, 18 Nov 2020 19:39:08:  28000000 
INFO  @ Wed, 18 Nov 2020 19:39:11:  29000000 
INFO  @ Wed, 18 Nov 2020 19:39:15:  30000000 
INFO  @ Wed, 18 Nov 2020 19:39:18:  31000000 
INFO  @ Wed, 18 Nov 2020 19:39:21:  32000000 
INFO  @ Wed, 18 Nov 2020 19:39:24:  33000000 
INFO  @ Wed, 18 Nov 2020 19:39:27:  34000000 
INFO  @ Wed, 18 Nov 2020 19:39:30:  35000000 
INFO  @ Wed, 18 Nov 2020 19:39:33:  36000000 
INFO  @ Wed, 18 Nov 2020 19:39:36:  37000000 
INFO  @ Wed, 18 Nov 2020 19:39:39:  38000000 
INFO  @ Wed, 18 Nov 2020 19:39:42:  39000000 
INFO  @ Wed, 18 Nov 2020 19:39:45:  40000000 
INFO  @ Wed, 18 Nov 2020 19:39:48:  41000000 
INFO  @ Wed, 18 Nov 2020 19:39:51:  42000000 
INFO  @ Wed, 18 Nov 2020 19:39:54:  43000000 
INFO  @ Wed, 18 Nov 2020 19:39:57:  44000000 
INFO  @ Wed, 18 Nov 2020 19:40:00:  45000000 
INFO  @ Wed, 18 Nov 2020 19:40:03:  46000000 
INFO  @ Wed, 18 Nov 2020 19:40:06:  47000000 
INFO  @ Wed, 18 Nov 2020 19:40:09:  48000000 
INFO  @ Wed, 18 Nov 2020 19:40:12:  49000000 
INFO  @ Wed, 18 Nov 2020 19:40:15:  50000000 
INFO  @ Wed, 18 Nov 2020 19:40:18:  51000000 
INFO  @ Wed, 18 Nov 2020 19:40:22:  52000000 
INFO  @ Wed, 18 Nov 2020 19:40:25:  53000000 
INFO  @ Wed, 18 Nov 2020 19:40:28:  54000000 
INFO  @ Wed, 18 Nov 2020 19:40:31:  55000000 
INFO  @ Wed, 18 Nov 2020 19:40:34:  56000000 
INFO  @ Wed, 18 Nov 2020 19:40:37:  57000000 
INFO  @ Wed, 18 Nov 2020 19:40:40:  58000000 
INFO  @ Wed, 18 Nov 2020 19:40:43:  59000000 
INFO  @ Wed, 18 Nov 2020 19:40:46:  60000000 
INFO  @ Wed, 18 Nov 2020 19:40:49:  61000000 
INFO  @ Wed, 18 Nov 2020 19:40:52:  62000000 
INFO  @ Wed, 18 Nov 2020 19:40:55:  63000000 
INFO  @ Wed, 18 Nov 2020 19:40:58:  64000000 
INFO  @ Wed, 18 Nov 2020 19:41:02:  65000000 
INFO  @ Wed, 18 Nov 2020 19:41:05:  66000000 
INFO  @ Wed, 18 Nov 2020 19:41:08:  67000000 
INFO  @ Wed, 18 Nov 2020 19:41:11:  68000000 
INFO  @ Wed, 18 Nov 2020 19:41:14:  69000000 
INFO  @ Wed, 18 Nov 2020 19:41:17:  70000000 
INFO  @ Wed, 18 Nov 2020 19:41:20:  71000000 
INFO  @ Wed, 18 Nov 2020 19:41:23:  72000000 
INFO  @ Wed, 18 Nov 2020 19:41:26:  73000000 
INFO  @ Wed, 18 Nov 2020 19:41:29:  74000000 
INFO  @ Wed, 18 Nov 2020 19:41:32:  75000000 
INFO  @ Wed, 18 Nov 2020 19:41:35:  76000000 
INFO  @ Wed, 18 Nov 2020 19:41:38:  77000000 
INFO  @ Wed, 18 Nov 2020 19:41:41:  78000000 
INFO  @ Wed, 18 Nov 2020 19:41:44:  79000000 
INFO  @ Wed, 18 Nov 2020 19:41:48:  80000000 
INFO  @ Wed, 18 Nov 2020 19:41:51:  81000000 
INFO  @ Wed, 18 Nov 2020 19:41:54:  82000000 
INFO  @ Wed, 18 Nov 2020 19:41:56:  83000000 
INFO  @ Wed, 18 Nov 2020 19:42:00:  84000000 
INFO  @ Wed, 18 Nov 2020 19:42:03:  85000000 
INFO  @ Wed, 18 Nov 2020 19:42:06:  86000000 
INFO  @ Wed, 18 Nov 2020 19:42:09:  87000000 
INFO  @ Wed, 18 Nov 2020 19:42:12:  88000000 
INFO  @ Wed, 18 Nov 2020 19:42:15:  89000000 
INFO  @ Wed, 18 Nov 2020 19:42:18:  90000000 
INFO  @ Wed, 18 Nov 2020 19:42:21:  91000000 
INFO  @ Wed, 18 Nov 2020 19:42:24:  92000000 
INFO  @ Wed, 18 Nov 2020 19:42:27:  93000000 
INFO  @ Wed, 18 Nov 2020 19:42:30:  94000000 
INFO  @ Wed, 18 Nov 2020 19:42:33:  95000000 
INFO  @ Wed, 18 Nov 2020 19:42:33: 95032218 reads have been read. 
INFO  @ Wed, 18 Nov 2020 19:42:35: #1.2 read input tags... 
INFO  @ Wed, 18 Nov 2020 19:42:38:  1000000 
INFO  @ Wed, 18 Nov 2020 19:42:41:  2000000 
INFO  @ Wed, 18 Nov 2020 19:42:44:  3000000 
INFO  @ Wed, 18 Nov 2020 19:42:47:  4000000 
INFO  @ Wed, 18 Nov 2020 19:42:51:  5000000 
INFO  @ Wed, 18 Nov 2020 19:42:54:  6000000 
INFO  @ Wed, 18 Nov 2020 19:42:57:  7000000 
INFO  @ Wed, 18 Nov 2020 19:43:00:  8000000 
INFO  @ Wed, 18 Nov 2020 19:43:03:  9000000 
INFO  @ Wed, 18 Nov 2020 19:43:06:  10000000 
INFO  @ Wed, 18 Nov 2020 19:43:09:  11000000 
INFO  @ Wed, 18 Nov 2020 19:43:13:  12000000 
INFO  @ Wed, 18 Nov 2020 19:43:16:  13000000 
INFO  @ Wed, 18 Nov 2020 19:43:19:  14000000 
INFO  @ Wed, 18 Nov 2020 19:43:22:  15000000 
INFO  @ Wed, 18 Nov 2020 19:43:25:  16000000 
INFO  @ Wed, 18 Nov 2020 19:43:29:  17000000 
INFO  @ Wed, 18 Nov 2020 19:43:32:  18000000 
INFO  @ Wed, 18 Nov 2020 19:43:35:  19000000 
INFO  @ Wed, 18 Nov 2020 19:43:38:  20000000 
INFO  @ Wed, 18 Nov 2020 19:43:42:  21000000 
INFO  @ Wed, 18 Nov 2020 19:43:45:  22000000 
INFO  @ Wed, 18 Nov 2020 19:43:48:  23000000 
INFO  @ Wed, 18 Nov 2020 19:43:51:  24000000 
INFO  @ Wed, 18 Nov 2020 19:43:54:  25000000 
INFO  @ Wed, 18 Nov 2020 19:43:58:  26000000 
INFO  @ Wed, 18 Nov 2020 19:44:01:  27000000 
INFO  @ Wed, 18 Nov 2020 19:44:04:  28000000 
INFO  @ Wed, 18 Nov 2020 19:44:07:  29000000 
INFO  @ Wed, 18 Nov 2020 19:44:10:  30000000 
INFO  @ Wed, 18 Nov 2020 19:44:13:  31000000 
INFO  @ Wed, 18 Nov 2020 19:44:16:  32000000 
INFO  @ Wed, 18 Nov 2020 19:44:20:  33000000 
INFO  @ Wed, 18 Nov 2020 19:44:23:  34000000 
INFO  @ Wed, 18 Nov 2020 19:44:26:  35000000 
INFO  @ Wed, 18 Nov 2020 19:44:29:  36000000 
INFO  @ Wed, 18 Nov 2020 19:44:32:  37000000 
INFO  @ Wed, 18 Nov 2020 19:44:35:  38000000 
INFO  @ Wed, 18 Nov 2020 19:44:39:  39000000 
INFO  @ Wed, 18 Nov 2020 19:44:42:  40000000 
INFO  @ Wed, 18 Nov 2020 19:44:45:  41000000 
INFO  @ Wed, 18 Nov 2020 19:44:49:  42000000 
INFO  @ Wed, 18 Nov 2020 19:44:52:  43000000 
INFO  @ Wed, 18 Nov 2020 19:44:55:  44000000 
INFO  @ Wed, 18 Nov 2020 19:44:59:  45000000 
INFO  @ Wed, 18 Nov 2020 19:45:02:  46000000 
INFO  @ Wed, 18 Nov 2020 19:45:06:  47000000 
INFO  @ Wed, 18 Nov 2020 19:45:09:  48000000 
INFO  @ Wed, 18 Nov 2020 19:45:12:  49000000 
INFO  @ Wed, 18 Nov 2020 19:45:15:  50000000 
INFO  @ Wed, 18 Nov 2020 19:45:18:  51000000 
INFO  @ Wed, 18 Nov 2020 19:45:22:  52000000 
INFO  @ Wed, 18 Nov 2020 19:45:25:  53000000 
INFO  @ Wed, 18 Nov 2020 19:45:28:  54000000 
INFO  @ Wed, 18 Nov 2020 19:45:31:  55000000 
INFO  @ Wed, 18 Nov 2020 19:45:35:  56000000 
INFO  @ Wed, 18 Nov 2020 19:45:38:  57000000 
INFO  @ Wed, 18 Nov 2020 19:45:41:  58000000 
INFO  @ Wed, 18 Nov 2020 19:45:44:  59000000 
INFO  @ Wed, 18 Nov 2020 19:45:48:  60000000 
INFO  @ Wed, 18 Nov 2020 19:45:51:  61000000 
INFO  @ Wed, 18 Nov 2020 19:45:54:  62000000 
INFO  @ Wed, 18 Nov 2020 19:45:58:  63000000 
INFO  @ Wed, 18 Nov 2020 19:46:01:  64000000 
INFO  @ Wed, 18 Nov 2020 19:46:04:  65000000 
INFO  @ Wed, 18 Nov 2020 19:46:08:  66000000 
INFO  @ Wed, 18 Nov 2020 19:46:11:  67000000 
INFO  @ Wed, 18 Nov 2020 19:46:14:  68000000 
INFO  @ Wed, 18 Nov 2020 19:46:17:  69000000 
INFO  @ Wed, 18 Nov 2020 19:46:21:  70000000 
INFO  @ Wed, 18 Nov 2020 19:46:24:  71000000 
INFO  @ Wed, 18 Nov 2020 19:46:27:  72000000 
INFO  @ Wed, 18 Nov 2020 19:46:30:  73000000 
INFO  @ Wed, 18 Nov 2020 19:46:34:  74000000 
INFO  @ Wed, 18 Nov 2020 19:46:37:  75000000 
INFO  @ Wed, 18 Nov 2020 19:46:40:  76000000 
INFO  @ Wed, 18 Nov 2020 19:46:43:  77000000 
INFO  @ Wed, 18 Nov 2020 19:46:46:  78000000 
INFO  @ Wed, 18 Nov 2020 19:46:49:  79000000 
INFO  @ Wed, 18 Nov 2020 19:46:53:  80000000 
INFO  @ Wed, 18 Nov 2020 19:46:56:  81000000 
INFO  @ Wed, 18 Nov 2020 19:46:59:  82000000 
INFO  @ Wed, 18 Nov 2020 19:47:02:  83000000 
INFO  @ Wed, 18 Nov 2020 19:47:05:  84000000 
INFO  @ Wed, 18 Nov 2020 19:47:09:  85000000 
INFO  @ Wed, 18 Nov 2020 19:47:12:  86000000 
INFO  @ Wed, 18 Nov 2020 19:47:15:  87000000 
INFO  @ Wed, 18 Nov 2020 19:47:18:  88000000 
INFO  @ Wed, 18 Nov 2020 19:47:22:  89000000 
INFO  @ Wed, 18 Nov 2020 19:47:25:  90000000 
INFO  @ Wed, 18 Nov 2020 19:47:28:  91000000 
INFO  @ Wed, 18 Nov 2020 19:47:31:  92000000 
INFO  @ Wed, 18 Nov 2020 19:47:34:  93000000 
INFO  @ Wed, 18 Nov 2020 19:47:37:  94000000 
INFO  @ Wed, 18 Nov 2020 19:47:40:  95000000 
INFO  @ Wed, 18 Nov 2020 19:47:44:  96000000 
INFO  @ Wed, 18 Nov 2020 19:47:47:  97000000 
INFO  @ Wed, 18 Nov 2020 19:47:50:  98000000 
INFO  @ Wed, 18 Nov 2020 19:47:53:  99000000 
INFO  @ Wed, 18 Nov 2020 19:47:56:  100000000 
INFO  @ Wed, 18 Nov 2020 19:48:00:  101000000 
INFO  @ Wed, 18 Nov 2020 19:48:03:  102000000 
INFO  @ Wed, 18 Nov 2020 19:48:06:  103000000 
INFO  @ Wed, 18 Nov 2020 19:48:09:  104000000 
INFO  @ Wed, 18 Nov 2020 19:48:12:  105000000 
INFO  @ Wed, 18 Nov 2020 19:48:15:  106000000 
INFO  @ Wed, 18 Nov 2020 19:48:19:  107000000 
INFO  @ Wed, 18 Nov 2020 19:48:22:  108000000 
INFO  @ Wed, 18 Nov 2020 19:48:25:  109000000 
INFO  @ Wed, 18 Nov 2020 19:48:28:  110000000 
INFO  @ Wed, 18 Nov 2020 19:48:32:  111000000 
INFO  @ Wed, 18 Nov 2020 19:48:35:  112000000 
INFO  @ Wed, 18 Nov 2020 19:48:38:  113000000 
INFO  @ Wed, 18 Nov 2020 19:48:41:  114000000 
INFO  @ Wed, 18 Nov 2020 19:48:44:  115000000 
INFO  @ Wed, 18 Nov 2020 19:48:47:  116000000 
INFO  @ Wed, 18 Nov 2020 19:48:51:  117000000 
INFO  @ Wed, 18 Nov 2020 19:48:54:  118000000 
INFO  @ Wed, 18 Nov 2020 19:48:57:  119000000 
INFO  @ Wed, 18 Nov 2020 19:49:00:  120000000 
INFO  @ Wed, 18 Nov 2020 19:49:04:  121000000 
INFO  @ Wed, 18 Nov 2020 19:49:07:  122000000 
INFO  @ Wed, 18 Nov 2020 19:49:10:  123000000 
INFO  @ Wed, 18 Nov 2020 19:49:13:  124000000 
INFO  @ Wed, 18 Nov 2020 19:49:16:  125000000 
INFO  @ Wed, 18 Nov 2020 19:49:20:  126000000 
INFO  @ Wed, 18 Nov 2020 19:49:23:  127000000 
INFO  @ Wed, 18 Nov 2020 19:49:23: 127040449 reads have been read. 
INFO  @ Wed, 18 Nov 2020 19:49:24: #1 tag size is determined as 49 bps 
INFO  @ Wed, 18 Nov 2020 19:49:24: #1 tag size = 49.0 
INFO  @ Wed, 18 Nov 2020 19:49:24: #1  total tags in treatment: 95032218 
INFO  @ Wed, 18 Nov 2020 19:49:24: #1 user defined the maximum tags... 
INFO  @ Wed, 18 Nov 2020 19:49:24: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
INFO  @ Wed, 18 Nov 2020 19:49:25: #1  tags after filtering in treatment: 41525253 
INFO  @ Wed, 18 Nov 2020 19:49:25: #1  Redundant rate of treatment: 0.56 
INFO  @ Wed, 18 Nov 2020 19:49:25: #1  total tags in control: 127040449 
INFO  @ Wed, 18 Nov 2020 19:49:25: #1 user defined the maximum tags... 
INFO  @ Wed, 18 Nov 2020 19:49:25: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
INFO  @ Wed, 18 Nov 2020 19:49:25: #1  tags after filtering in control: 107990296 
INFO  @ Wed, 18 Nov 2020 19:49:25: #1  Redundant rate of control: 0.15 
INFO  @ Wed, 18 Nov 2020 19:49:25: #1 finished! 
INFO  @ Wed, 18 Nov 2020 19:49:25: #2 Build Peak Model... 
INFO  @ Wed, 18 Nov 2020 19:49:25: #2 looking for paired plus/minus strand peaks... 
INFO  @ Wed, 18 Nov 2020 19:49:33: #2 number of paired peaks: 89810 
INFO  @ Wed, 18 Nov 2020 19:49:33: start model_add_line... 
INFO  @ Wed, 18 Nov 2020 19:49:37: start X-correlation... 
INFO  @ Wed, 18 Nov 2020 19:49:37: end of X-cor 
INFO  @ Wed, 18 Nov 2020 19:49:37: #2 finished! 
INFO  @ Wed, 18 Nov 2020 19:49:37: #2 predicted fragment length is 275 bps 
INFO  @ Wed, 18 Nov 2020 19:49:37: #2 alternative fragment length(s) may be 275 bps 
INFO  @ Wed, 18 Nov 2020 19:49:37: #2.2 Generate R script for model : A1EVK4D0.F1EVD0IP_model.r 
INFO  @ Wed, 18 Nov 2020 19:49:37: #3 Call peaks... 
INFO  @ Wed, 18 Nov 2020 19:49:37: #3 Pre-compute pvalue-qvalue table... 
INFO  @ Wed, 18 Nov 2020 19:55:08: #3 In the peak calling step, the following will be performed simultaneously: 
INFO  @ Wed, 18 Nov 2020 19:55:08: #3   Write bedGraph files for treatment pileup (after scaling if necessary)... A1EVK4D0.F1EVD0IP_treat_pileup.bdg 
INFO  @ Wed, 18 Nov 2020 19:55:08: #3   Write bedGraph files for control lambda (after scaling if necessary)... A1EVK4D0.F1EVD0IP_control_lambda.bdg 
INFO  @ Wed, 18 Nov 2020 19:55:08: #3   Pileup will be based on sequencing depth in treatment. 
INFO  @ Wed, 18 Nov 2020 19:55:08: #3 Call peaks for each chromosome... 
ValueError: cannot resize this array: it does not own its data
Exception ignored in: 'MACS2.IO.CallPeakUnit.clean_up_ndarray'
ValueError: cannot resize this array: it does not own its data
ValueError: cannot resize this array: it does not own its data
Exception ignored in: 'MACS2.IO.CallPeakUnit.clean_up_ndarray'
ValueError: cannot resize this array: it does not own its data
ValueError: cannot resize this array: it does not own its data
Exception ignored in: 'MACS2.IO.CallPeakUnit.clean_up_ndarray'
ValueError: cannot resize this array: it does not own its data
INFO  @ Wed, 18 Nov 2020 20:01:20: #4 Write output xls file... A1EVK4D0.F1EVD0IP_peaks.xls 
INFO  @ Wed, 18 Nov 2020 20:01:21: #4 Write peak in narrowPeak format file... A1EVK4D0.F1EVD0IP_peaks.narrowPeak 
INFO  @ Wed, 18 Nov 2020 20:01:21: #4 Write summits bed file... A1EVK4D0.F1EVD0IP_summits.bed 
INFO  @ Wed, 18 Nov 2020 20:01:21: Done! 
INFO  @ Wed, 18 Nov 2020 20:01:52:

**Comment by olegs** [comment]
Hello, hemantgujar, can you please check that created peak file is ok?

**Comment by olegs** [comment]
The original ticket in MACS2 issue tracker https://github.com/macs3-project/MACS/issues/122 suggests that probably you have some problems writing to `/tmp` folder?

**Comment by hemantgujar** [comment]
yes i found that thread later solved it. thanks.
